server:
  port: 8082
#  port: 0

spring:
  application:
    name: content-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/content_center?useSSL=false
      username: root
      password: mysql
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000